### ISSUE TITLE
XS_FUNCTIONS error

### ISSUE THREAD

**Issue by jerrysh** [RhubarbSin/xenserver-admin-scripts#1]
hello
 i run the xenserver-admin-scripts failed. it prompt "XS_FUNCTIONS error" 
i cant not find why
thanks

**Comment by RhubarbSin** [comment]
What Linux distribution and version are you using? Post the output of `bash -x xs-vm-summary`.

**Comment by jerrysh** [comment]
i sorry to run your script in Xenserver 6.2
it must be use in remote linux OS ?

**Comment by RhubarbSin** [comment]
You can use the scripts in a XenServer control domain (dom0) or on another host. You will probably need to set the XE_EXTRA_ARGS environment variable or the XE_SERVER, XE_USER, XE_PASSWORD environment variables (you can see the default assignments in `xs-functions`).

**Comment by jerrysh** [comment]
RhubarbSin
thank u , i often unable to visit github
i will try again
